#!/usr/bin/env python3
"""
LEGO - Lattice Elemental Geometry Operations
Python wrapper for the LEGO crystal structure generator.

Usage:
    from lego import Lego

    lego = Lego()
    result = lego.run("params.param")
    print(result)

    # Or with keyword arguments:
    result = lego.run(
        structure="fcc",
        lattice_const=3.615,
        box_x=100, box_y=100, box_z=100,
        new_x="1 1 0", new_z="0 0 1",
        outfile="Cu_fcc.imd"
    )
"""

import os
import re
import subprocess
import tempfile
from pathlib import Path


class LegoResult:
    """Result from a LEGO run."""

    def __init__(self, stdout, stderr, returncode, outfile=None):
        self.stdout = stdout
        self.stderr = stderr
        self.returncode = returncode
        self.outfile = outfile
        self.success = (returncode == 0)

        # Parse metadata from stdout
        self.total_atoms = self._parse_int(r"Total atoms:\s+(\d+)")
        self.box = self._parse_vec3(
            r"Box:\s+([\d.]+)\s+x\s+([\d.]+)\s+x\s+([\d.]+)")
        self.repeat_dist = self._parse_vec3(
            r"Min repeat:\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)")

    def _parse_int(self, pattern):
        m = re.search(pattern, self.stdout)
        return int(m.group(1)) if m else None

    def _parse_vec3(self, pattern):
        m = re.search(pattern, self.stdout)
        if m:
            return (float(m.group(1)), float(m.group(2)), float(m.group(3)))
        return None

    def __repr__(self):
        return (f"LegoResult(atoms={self.total_atoms}, "
                f"box={self.box}, repeat={self.repeat_dist}, "
                f"success={self.success})")


class Lego:
    """Wrapper for the LEGO crystal structure generator binary."""

    def __init__(self, binary=None):
        """Initialize with path to the lego binary.

        Args:
            binary: Path to lego executable. If None, searches PATH
                    and common locations.
        """
        if binary:
            self.binary = binary
        else:
            self.binary = self._find_binary()

    def _find_binary(self):
        """Find the lego binary."""
        # Check PATH
        import shutil
        path = shutil.which("lego")
        if path:
            return path

        # Check relative to this script
        script_dir = Path(__file__).parent.parent
        candidates = [
            script_dir / "lego",
            script_dir / "build" / "lego",
        ]
        for c in candidates:
            if c.exists() and os.access(str(c), os.X_OK):
                return str(c)

        raise FileNotFoundError(
            "Cannot find 'lego' binary. Pass the path explicitly: "
            "Lego(binary='/path/to/lego')")

    def run(self, param_file=None, **kwargs):
        """Run LEGO with a parameter file or keyword arguments.

        Args:
            param_file: Path to a parameter file.
            **kwargs: Parameter key-value pairs. Used to generate a
                      temporary parameter file if param_file is not given.

        Returns:
            LegoResult with parsed output metadata.
        """
        if param_file:
            return self._run_file(param_file)
        elif kwargs:
            return self._run_kwargs(kwargs)
        else:
            raise ValueError("Provide either param_file or keyword arguments")

    def _run_file(self, param_file):
        """Run with an existing parameter file."""
        result = subprocess.run(
            [self.binary, param_file],
            capture_output=True, text=True)

        outfile = self._extract_outfile(param_file)

        return LegoResult(
            result.stdout, result.stderr, result.returncode, outfile)

    def _run_kwargs(self, kwargs):
        """Generate a parameter file from kwargs and run."""
        # Create temporary parameter file
        fd, tmpfile = tempfile.mkstemp(suffix=".param", prefix="lego_")
        try:
            with os.fdopen(fd, 'w') as f:
                f.write("# Auto-generated by lego.py\n")
                for key, value in kwargs.items():
                    f.write(f"{key}\t{value}\n")

            result = self._run_file(tmpfile)
            result.outfile = kwargs.get("outfile")
            return result
        finally:
            os.unlink(tmpfile)

    def _extract_outfile(self, param_file):
        """Extract outfile name from a parameter file."""
        try:
            with open(param_file) as f:
                for line in f:
                    line = line.strip()
                    if line.startswith('#') or not line:
                        continue
                    parts = line.split()
                    if len(parts) >= 2 and parts[0].lower() == "outfile":
                        return parts[1]
        except (IOError, OSError):
            pass
        return None

    @staticmethod
    def cif_to_poscar(cif_file, poscar_file=None):
        """Convert a CIF file to POSCAR format using pymatgen.

        Args:
            cif_file: Path to input CIF file.
            poscar_file: Path to output POSCAR file. If None, uses
                         the CIF filename with .poscar extension.

        Returns:
            Path to the output POSCAR file.
        """
        try:
            from pymatgen.io.cif import CifParser
            from pymatgen.io.vasp import Poscar
        except ImportError:
            raise RuntimeError(
                "pymatgen is required for CIF conversion. "
                "Install with: pip install pymatgen")

        if poscar_file is None:
            poscar_file = Path(cif_file).with_suffix(".poscar")

        structure = CifParser(str(cif_file)).parse_structures()[0]
        poscar = Poscar(structure)
        poscar.write_file(str(poscar_file))

        return str(poscar_file)

    @staticmethod
    def ase_to_poscar(structure_file, poscar_file=None, format=None):
        """Convert any structure file to POSCAR using ASE.

        Args:
            structure_file: Path to input structure file.
            poscar_file: Path to output POSCAR file.
            format: ASE format string (auto-detected if None).

        Returns:
            Path to the output POSCAR file.
        """
        try:
            from ase.io import read, write
        except ImportError:
            raise RuntimeError(
                "ASE is required for structure conversion. "
                "Install with: pip install ase")

        if poscar_file is None:
            poscar_file = Path(structure_file).with_suffix(".poscar")

        atoms = read(str(structure_file), format=format)
        write(str(poscar_file), atoms, format='vasp')

        return str(poscar_file)


def main():
    """CLI interface for quick runs."""
    import argparse

    parser = argparse.ArgumentParser(
        description="LEGO Python wrapper")
    parser.add_argument("param_file", nargs="?",
                        help="Parameter file to run")
    parser.add_argument("--binary", default=None,
                        help="Path to lego binary")
    parser.add_argument("--cif-to-poscar", nargs=2,
                        metavar=("CIF", "POSCAR"),
                        help="Convert CIF to POSCAR")

    args = parser.parse_args()

    if args.cif_to_poscar:
        result = Lego.cif_to_poscar(args.cif_to_poscar[0],
                                    args.cif_to_poscar[1])
        print(f"Converted to: {result}")
        return

    if not args.param_file:
        parser.print_help()
        return

    lego = Lego(binary=args.binary)
    result = lego.run(args.param_file)

    if result.success:
        print(result)
    else:
        print(f"LEGO failed (exit code {result.returncode})")
        if result.stderr:
            print(result.stderr)


if __name__ == "__main__":
    main()
